# DataSource settings: set here your own configurations for the database 
# connection. In this example we have "netgloo_blog" as database name and 
# "root" as username and password.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp
    username: ****
    password: *****
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform:  org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update    

logging:
  level: 
    ROOT: DEBUG,TRACE,INFO
    com.smartd.backoffice: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /home/remya/Downloads/application.log
    
